### ISSUE TITLE
Small update

### ISSUE THREAD

**Issue by Kevsosmooth** [aleaforny/python-invoice-generator#4]
I know you are not the owner but there is definitely a need for a new update, you are not allowed to use the download method anymore unless you add the api key which was not necessary before.

**Comment by aleaforny** [comment]
Thanks for the hint.

I've updated the script, can you try again? It should work now! 
(you can update the `API_KEY = "SET_YOUR_API_KEY_HERE"` settings)

Thanks

**Comment by Kevsosmooth** [comment]
Lastly do you know if it’s possible to change the date of invoice creation.
Because in know you get local time but i want to be able to set invoice
date if possible not sure

Thank you,

*Kevin S. *

**Comment by aleaforny** [comment]
You should be able to add the argument **`date`** while constructing the Invoice :  

```
invoice = InvoiceGenerator(
    sender="Invoiced, Inc.",
    to="Parag",
    logo="https://invoiced.com/img/logo-invoice.png",
    number=1,
    notes="Thanks for your business!",
    shipping=50,
   date=my_date  # <================== HERE
)
```

be careful as it expects a datetime object though.
